langugage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adamlakos/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true adamlakos/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-495601641765"
  bucket_path: "docker-react"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY